# Generated by Django 4.1.3 on 2022-11-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudo_forms', '0002_alter_aluno_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.CharField(choices=[('Curso Técnico', 'Curso Técnico'), ('Curso Superior', 'Curso Superior')], default='Curso Técnico', max_length=100),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='Feminino', max_length=100),
        ),
    ]
