# Generated by Django 4.1.5 on 2023-01-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudo_forms', '0003_alter_aluno_curso_alter_aluno_sexo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.CharField(choices=[('Curso Técnico', 'Curso Técnico'), ('Curso Superior', 'Curso Superior')], max_length=100),
        ),
    ]
